// Emit Postgres DDL from a Drizzle pgTable / pgSchema(...).table object.
//
// Why: samesake creates schemas at runtime (per-project schema names, env-
// configurable system schema), so drizzle-kit's compile-time migration
// pipeline doesn't fit. We need DDL strings at boot/apply time AND fluent
// pgTable for queries. Without this emitter we hand-maintain both surfaces
// and they drift (we've already paid for that — see commit history).
//
// Scope (deliberately narrow): only what our 10 system tables actually use.
//   - column types: text, bigint, integer, jsonb, timestamp with time zone,
//     numeric(p,s), double precision, boolean, customType (e.g. vector)
//   - constraints: NOT NULL, single-col PK, single-col UNIQUE, generated
//     identity, composite PK, composite UNIQUE, CHECK, FOREIGN KEY (with
//     ON DELETE)
//   - defaults: scalar literals, SQL expressions (e.g. now()), jsonb objects
//   - indexes: btree, multi-column, named
//
// What's intentionally NOT here:
//   - HNSW / GIN indexes, partial WHERE, USING WITH (...) — those are on
//     per-project entity tables whose columns are user-defined at runtime;
//     they stay in src/core/schema-gen.ts as hand-written SQL.
//
// New column type / constraint shape unsupported by this emitter throws
// loudly so adding it is a deliberate change, not a silent miss.
import { getTableConfig, PgDialect } from "drizzle-orm/pg-core";
// Use the same input type as getTableConfig so we accept every concrete
// PgTableWithColumns<...> shape without forcing call sites to cast.
type AnyTable = Parameters<typeof getTableConfig>[0];
import { is, SQL } from "drizzle-orm";

const dialect = new PgDialect();

function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

function renderDefault(col: { default: unknown; defaultFn?: unknown; getSQLType: () => string }): string | null {
  if (col.defaultFn) {
    throw new Error(
      `defaultFn() column defaults aren't supported by tableToDDL (they're JS-side); ` +
      `use sql\`...\` instead so the default lives in the database.`
    );
  }
  const v = col.default;
  if (v === undefined) return null;
  if (v === null) return "null";
  if (is(v, SQL)) {
    const { sql: s } = dialect.sqlToQuery(v);
    return s;
  }
  if (typeof v === "number" || typeof v === "boolean" || typeof v === "bigint") {
    return String(v);
  }
  if (typeof v === "string") {
    return `'${v.replace(/'/g, "''")}'`;
  }
  if (typeof v === "object") {
    // jsonb defaults: an object literal becomes '{...}'::jsonb. The column's
    // SQL type tells us the cast.
    const sqlType = col.getSQLType();
    if (sqlType === "jsonb" || sqlType === "json") {
      return `'${JSON.stringify(v).replace(/'/g, "''")}'::${sqlType}`;
    }
  }
  throw new Error(
    `unsupported column default for tableToDDL: ${JSON.stringify(v)} (column type ${col.getSQLType()})`
  );
}

function renderColumn(col: ReturnType<typeof getTableConfig>["columns"][number]): string {
  const parts: string[] = [quoteIdent(col.name), col.getSQLType()];

  // Identity columns: Drizzle's column.generatedIdentity holds the type
  // (alwaysAs | byDefaultAs) plus sequence options.
  const ident = (col as unknown as { generatedIdentity?: { type: "always" | "byDefault" } }).generatedIdentity;
  if (ident) {
    parts.push(
      ident.type === "always"
        ? "GENERATED ALWAYS AS IDENTITY"
        : "GENERATED BY DEFAULT AS IDENTITY"
    );
  }

  if (col.notNull) parts.push("NOT NULL");

  if (col.hasDefault) {
    const def = renderDefault(col);
    if (def !== null) parts.push(`DEFAULT ${def}`);
  }

  if ((col as { primary?: boolean }).primary) parts.push("PRIMARY KEY");
  if (col.isUnique) parts.push("UNIQUE");

  return parts.join(" ");
}

export interface EmitOptions {
  /** Wrap CREATE TABLE / CREATE INDEX with IF NOT EXISTS for idempotency. Default true. */
  ifNotExists?: boolean;
}

/**
 * Emit CREATE TABLE + CREATE INDEX statements for a Drizzle table.
 * Returns a single string with statements separated by blank lines, ready
 * to pass to db.execute(sql.raw(...)).
 */
export function tableToDDL(table: AnyTable, opts: EmitOptions = {}): string {
  const ifNotExists = opts.ifNotExists ?? true;
  const cfg = getTableConfig(table);
  const schemaPart = cfg.schema ? `${quoteIdent(cfg.schema)}.` : "";
  const tableRef = `${schemaPart}${quoteIdent(cfg.name)}`;

  const colDefs = cfg.columns.map(renderColumn);

  // Composite primary keys
  for (const pk of cfg.primaryKeys) {
    const cols = pk.columns.map((c) => quoteIdent(c.name)).join(", ");
    colDefs.push(`PRIMARY KEY (${cols})`);
  }

  // Composite unique constraints
  for (const uq of cfg.uniqueConstraints) {
    const cols = uq.columns.map((c) => quoteIdent(c.name)).join(", ");
    const nameClause = uq.name ? `CONSTRAINT ${quoteIdent(uq.name)} ` : "";
    colDefs.push(`${nameClause}UNIQUE (${cols})`);
  }

  // CHECK constraints
  for (const ck of cfg.checks) {
    const { sql: s } = dialect.sqlToQuery(ck.value);
    const nameClause = ck.name ? `CONSTRAINT ${quoteIdent(ck.name)} ` : "";
    colDefs.push(`${nameClause}CHECK (${s})`);
  }

  // FOREIGN KEY constraints — render as table-level constraints with the
  // referenced table fully schema-qualified so the DDL works regardless of
  // search_path.
  for (const fk of cfg.foreignKeys) {
    const ref = fk.reference();
    const localCols = ref.columns.map((c) => quoteIdent(c.name)).join(", ");
    const foreignCols = ref.foreignColumns.map((c) => quoteIdent(c.name)).join(", ");
    const foreignTableCfg = getTableConfig(ref.foreignTable as AnyTable);
    const foreignTableRef = `${foreignTableCfg.schema ? `${quoteIdent(foreignTableCfg.schema)}.` : ""}${quoteIdent(foreignTableCfg.name)}`;
    // Skip "no action" — it's the Postgres default; emitting it is just noise.
    const isMeaningful = (a: string | undefined): boolean =>
      !!a && a.toLowerCase() !== "no action";
    const onDelete = isMeaningful(fk.onDelete) ? ` ON DELETE ${fk.onDelete!.toUpperCase()}` : "";
    const onUpdate = isMeaningful(fk.onUpdate) ? ` ON UPDATE ${fk.onUpdate!.toUpperCase()}` : "";
    colDefs.push(`FOREIGN KEY (${localCols}) REFERENCES ${foreignTableRef} (${foreignCols})${onDelete}${onUpdate}`);
  }

  const stmts: string[] = [];
  stmts.push(
    `CREATE TABLE ${ifNotExists ? "IF NOT EXISTS " : ""}${tableRef} (\n  ${colDefs.join(",\n  ")}\n);`
  );

  // Indexes — only the shapes our system tables use (btree, multi-col, named).
  // Anything more exotic (partial, GIN, HNSW, USING WITH) belongs in a
  // hand-written SQL escape hatch, not here.
  for (const idx of cfg.indexes) {
    const cfgInner = (idx as { config: { name?: string; columns: Array<{ name: string }>; method?: string; unique?: boolean; where?: SQL; with?: Record<string, unknown> } }).config;
    if (cfgInner.where || cfgInner.with) {
      throw new Error(
        `index '${cfgInner.name}' uses partial WHERE or WITH options — ` +
        `these aren't part of tableToDDL's scope; emit them as hand-written SQL.`
      );
    }
    if (cfgInner.method && cfgInner.method !== "btree") {
      throw new Error(
        `index '${cfgInner.name}' uses method '${cfgInner.method}' — only btree ` +
        `is supported by tableToDDL (GIN/HNSW are hand-written for per-project entity tables).`
      );
    }
    const name = cfgInner.name ?? `${cfg.name}_${cfgInner.columns.map((c) => c.name).join("_")}_idx`;
    const cols = cfgInner.columns.map((c) => quoteIdent(c.name)).join(", ");
    stmts.push(
      `CREATE ${cfgInner.unique ? "UNIQUE " : ""}INDEX ${ifNotExists ? "IF NOT EXISTS " : ""}${quoteIdent(name)} ON ${tableRef} (${cols});`
    );
  }

  return stmts.join("\n\n") + "\n";
}

/** Convenience for emitting multiple tables at once. */
export function tablesToDDL(tables: AnyTable[], opts: EmitOptions = {}): string {
  return tables.map((t) => tableToDDL(t, opts)).join("\n");
}
