/**
 * System-level DDL applied once when the matcher boots. Idempotent.
 *
 * Table DDL is derived from src/db/schema/system.ts via tableToDDL — single
 * source of truth. Only the non-table DDL (extensions, PL/pgSQL functions,
 * units-alias seed data) is hand-written here, because Drizzle pgTable
 * doesn't model those surfaces.
 *
 * Schema name is the matcher's configured system schema (passed in by
 * createMatcher via ctx). Per-project match functions generated by
 * schema-gen.ts call back into these utility functions via the same schema
 * qualifier.
 */
import { tablesToDDL } from "./ddl.ts";
import { makeSystemTables } from "./schema/system.ts";

export function getSystemDDL(schema: string): string {
  if (!/^[a-z_][a-z0-9_]{0,62}$/i.test(schema)) {
    throw new Error(`invalid schema value: ${JSON.stringify(schema)}`);
  }
  const s = schema;
  const sys = makeSystemTables(schema);

  // Extensions, schema, then table DDL (emitted from schemas), then PL/pgSQL
  // functions + the units-alias seed. Order matters: tables before functions
  // that reference them, seed before any code that selects from the table.
  return [
    `CREATE EXTENSION IF NOT EXISTS vector;`,
    `CREATE EXTENSION IF NOT EXISTS pg_trgm;`,
    `CREATE EXTENSION IF NOT EXISTS unaccent;`,
    `CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;`,
    `CREATE SCHEMA IF NOT EXISTS ${s};`,

    tablesToDDL([
      sys.samesakeProjects,
      sys.samesakeEmbedCache,
      sys.samesakeParseCache,
      sys.samesakeStageCache,
      sys.samesakeUnitsAlias,
      sys.samesakeCorrections,
    ]),

    `ALTER TABLE ${s}.samesake_projects ADD COLUMN IF NOT EXISTS api_key text;`,

    // ── samesake_normalise — lowercase + unaccent + strip ASCII punct ────
    `
    CREATE OR REPLACE FUNCTION ${s}.samesake_normalise(input text)
    RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $fn$
      SELECT trim(
        regexp_replace(
          regexp_replace(
            lower(unaccent(coalesce(input, ''))),
            '[[:punct:]]+',
            ' ',
            'g'
          ),
          '[[:space:]]+', ' ', 'g'
        )
      );
    $fn$;`,

    // ── samesake_phonetic — Indic-Soundex-style cross-script hash ────────
    `
    CREATE OR REPLACE FUNCTION ${s}.samesake_phonetic(input text)
    RETURNS text LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE AS $fn$
    DECLARE
      s text;
    BEGIN
      s := lower(coalesce(input, ''));

      -- Aspirate-strip: in Latin transliterations of Indic names, 'h'
      -- after d/t/k/p/g/b/c/j marks aspiration of the preceding consonant
      -- and has no separate phonetic class in our alphabet. The native
      -- script writes a different consonant character (e.g. द vs ध, க has
      -- no 'kh' counterpart in Tamil), so dropping the 'h' here is what
      -- makes 'Maaladhi' ≡ 'மாலதி' and 'Mukhesh' ≡ 'मुकेश'. Word-initial
      -- 'h' and 'sh' digraph are unaffected.
      s := regexp_replace(s, '([dtkpgbcj])h', '\\1', 'g');

      -- Same 8-letter alphabet across scripts so 'Amma' ≡ 'අම්මා' ≡ 'அம்மா'.
      -- SINHALA
      s := translate(s, 'කඛගඝ',     'KKKK');
      s := translate(s, 'චඡජඣ',     'CCCC');
      s := translate(s, 'ටඨඩඪතථදධ', 'TTTTTTTT');
      s := translate(s, 'පඵබභ',     'PPPP');
      s := translate(s, 'සශෂ',      'SSS');
      s := translate(s, 'මනණඞඤං',   'NNNNNN');
      s := translate(s, 'ය',        'Y');
      s := translate(s, 'ර',        'R');
      s := translate(s, 'ලළ',       'LL');
      s := translate(s, 'වහ',       'VV');

      -- TAMIL
      -- NOTE: Tamil ச maps to S, not C, to align with how it is actually
      -- pronounced (and transliterated to Latin) in Sri Lankan and modern
      -- Indian Tamil — e.g. 'சில்' is romanised 'sil-', not 'chil-'. Tamil
      -- ஜ stays in the C class to align with Latin 'j' (which also → C).
      -- This is the load-bearing change for Tamil↔Latin same-name parity.
      s := translate(s, 'க',        'K');
      s := translate(s, 'ஞஙணநனம',   'NNNNNN');
      s := translate(s, 'ச',        'S');
      s := translate(s, 'ஜ',        'C');
      s := translate(s, 'டத',       'TT');
      s := translate(s, 'ற',        'R');
      s := translate(s, 'ப',        'P');
      s := translate(s, 'ஸஶஷ',      'SSS');
      s := translate(s, 'ய',        'Y');
      s := translate(s, 'ர',        'R');
      s := translate(s, 'லளழ',      'LLL');
      s := translate(s, 'வஹ',       'VV');

      -- LATIN
      s := translate(s, 'kgqx',     'KKKK');
      s := translate(s, 'cj',       'CC');
      s := translate(s, 'bp',       'PP');
      s := translate(s, 'dtf',      'TTT');
      s := translate(s, 'vwh',      'VVV');
      s := translate(s, 'mn',       'NN');
      s := translate(s, 'r',        'R');
      s := translate(s, 'l',        'L');
      s := translate(s, 'y',        'Y');
      s := translate(s, 'sz',       'SS');

      s := regexp_replace(s, '[^KCTPSNRLYVH]', '', 'g');
      s := regexp_replace(s, '(.)\\1+', '\\1', 'g');

      RETURN s;
    END;
    $fn$;`,

    // ── units-alias seed data (idempotent via ON CONFLICT) ───────────────
    `
    INSERT INTO ${s}.samesake_units_alias (alias_norm, canonical, family, factor_to_canonical) VALUES
      ('pcs','pcs','count',1), ('pc','pcs','count',1), ('piece','pcs','count',1), ('pieces','pcs','count',1),
      ('pccs','pcs','count',1), ('pisces','pcs','count',1), ('nos','pcs','count',1), ('no','pcs','count',1),
      ('item','pcs','count',1), ('unit','pcs','count',1), ('units','pcs','count',1),
      ('dozen','pcs','count',12), ('doz','pcs','count',12),
      ('pair','pcs','count',2), ('pairs','pcs','count',2),
      ('gross','pcs','count',144),
      ('g','g','mass',1), ('gm','g','mass',1), ('gram','g','mass',1), ('grams','g','mass',1),
      ('kg','g','mass',1000), ('kilo','g','mass',1000), ('kilogram','g','mass',1000),
      ('mg','g','mass',0.001),
      ('ml','ml','volume',1), ('cc','ml','volume',1),
      ('l','ml','volume',1000), ('ltr','ml','volume',1000), ('litre','ml','volume',1000),
      ('liter','ml','volume',1000),
      ('mm','mm','length',1), ('cm','mm','length',10), ('m','mm','length',1000),
      ('inch','mm','length',25.4),
      ('bottle','bottle','count',1), ('packet','packet','count',1), ('pack','packet','count',1),
      ('box','box','count',1), ('bag','bag','count',1)
    ON CONFLICT (alias_norm) DO NOTHING;`,

    // ── samesake_unit — resolve alias to canonical + family + factor ─────
    `
    CREATE OR REPLACE FUNCTION ${s}.samesake_unit(input text)
    RETURNS TABLE(canonical text, family text, factor numeric)
    LANGUAGE sql STABLE PARALLEL SAFE AS $fn$
      SELECT canonical, family, factor_to_canonical
      FROM ${s}.samesake_units_alias
      WHERE alias_norm = lower(trim(coalesce(input, '')));
    $fn$;`,
  ].join("\n");
}
