/**
 * System-level DDL applied once when the matcher boots. Idempotent.
 *
 * Table DDL is derived from src/db/schema/system.ts via tableToDDL — single
 * source of truth. Only the non-table DDL (extensions, PL/pgSQL functions,
 * units-alias seed data) is hand-written here, because Drizzle pgTable
 * doesn't model those surfaces.
 *
 * Schema name is the matcher's configured system schema (passed in by
 * createMatcher via ctx). Per-project match functions generated by
 * schema-gen.ts call back into these utility functions via the same schema
 * qualifier.
 */
import { tablesToDDL } from "./ddl.ts";
import { makeSystemTables } from "./schema/system.ts";
import type { PhoneticProvider } from "./postgres/phonetic.ts";

export function getSystemDDL(schema: string, phonetic?: PhoneticProvider): string {
  if (!/^[a-z_][a-z0-9_]{0,62}$/i.test(schema)) {
    throw new Error(`invalid schema value: ${JSON.stringify(schema)}`);
  }
  const s = schema;
  const sys = makeSystemTables(schema);

  // Extensions, schema, then table DDL (emitted from schemas), then PL/pgSQL
  // functions + the units-alias seed. Order matters: tables before functions
  // that reference them, seed before any code that selects from the table.
  return [
    `CREATE EXTENSION IF NOT EXISTS vector;`,
    `CREATE EXTENSION IF NOT EXISTS pg_trgm;`,
    `CREATE EXTENSION IF NOT EXISTS unaccent;`,
    `CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;`,
    `CREATE SCHEMA IF NOT EXISTS ${s};`,

    tablesToDDL([
      sys.samesakeProjects,
      sys.samesakeEmbedCache,
      sys.samesakeParseCache,
      sys.samesakeStageCache,
      sys.samesakeUnitsAlias,
      sys.samesakeCorrections,
    ]),

    `ALTER TABLE ${s}.samesake_projects ADD COLUMN IF NOT EXISTS api_key text;`,

    // ── samesake_normalise — lowercase + unaccent + strip ASCII punct ────
    `
    CREATE OR REPLACE FUNCTION ${s}.samesake_normalise(input text)
    RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $fn$
      SELECT trim(
        regexp_replace(
          regexp_replace(
            lower(unaccent(coalesce(input, ''))),
            '[[:punct:]]+',
            ' ',
            'g'
          ),
          '[[:space:]]+', ' ', 'g'
        )
      );
    $fn$;`,

    // samesake_phonetic — installed only when a PhoneticProvider is configured (default: none)
    ...(phonetic ? [phonetic.ddl(s)] : []),

    // ── units-alias seed data (idempotent via ON CONFLICT) ───────────────
    `
    INSERT INTO ${s}.samesake_units_alias (alias_norm, canonical, family, factor_to_canonical) VALUES
      ('pcs','pcs','count',1), ('pc','pcs','count',1), ('piece','pcs','count',1), ('pieces','pcs','count',1),
      ('pccs','pcs','count',1), ('pisces','pcs','count',1), ('nos','pcs','count',1), ('no','pcs','count',1),
      ('item','pcs','count',1), ('unit','pcs','count',1), ('units','pcs','count',1),
      ('dozen','pcs','count',12), ('doz','pcs','count',12),
      ('pair','pcs','count',2), ('pairs','pcs','count',2),
      ('gross','pcs','count',144),
      ('g','g','mass',1), ('gm','g','mass',1), ('gram','g','mass',1), ('grams','g','mass',1),
      ('kg','g','mass',1000), ('kilo','g','mass',1000), ('kilogram','g','mass',1000),
      ('mg','g','mass',0.001),
      ('ml','ml','volume',1), ('cc','ml','volume',1),
      ('l','ml','volume',1000), ('ltr','ml','volume',1000), ('litre','ml','volume',1000),
      ('liter','ml','volume',1000),
      ('mm','mm','length',1), ('cm','mm','length',10), ('m','mm','length',1000),
      ('inch','mm','length',25.4),
      ('bottle','bottle','count',1), ('packet','packet','count',1), ('pack','packet','count',1),
      ('box','box','count',1), ('bag','bag','count',1)
    ON CONFLICT (alias_norm) DO NOTHING;`,

    // ── samesake_unit — resolve alias to canonical + family + factor ─────
    `
    CREATE OR REPLACE FUNCTION ${s}.samesake_unit(input text)
    RETURNS TABLE(canonical text, family text, factor numeric)
    LANGUAGE sql STABLE PARALLEL SAFE AS $fn$
      SELECT canonical, family, factor_to_canonical
      FROM ${s}.samesake_units_alias
      WHERE alias_norm = lower(trim(coalesce(input, '')));
    $fn$;`,
  ].join("\n");
}
